### ISSUE TITLE
How to disable North Compensation on 3DM-CX5-AHRS 

### ISSUE THREAD

**Issue by peichunhuang-1** [LORD-MicroStrain/mip_sdk#88]
Can I disable the north compensation by this library? thanks for replying.
![IMG_2672](https://github.com/LORD-MicroStrain/mip_sdk/assets/60284084/a285fe3f-e964-4367-84da-7bdd8c4d5358)

**Comment by dacuster** [comment]
Hi @peichunhuang-1,
North compensation is labeled as `heading_enable` in the Complementary Filter command interface. Setting that value to false and writing that command to the device will disable it.

You can see the C implementations here:
-  [heading_enable](https://github.com/LORD-MicroStrain/mip_sdk/blob/2c3e4efe2d886cd3ad196c64d3704d6560c1ae1d/src/mip/definitions/commands_3dm.h#L1896)
- [mip_3dm_write_complementary_filter](https://github.com/LORD-MicroStrain/mip_sdk/blob/2c3e4efe2d886cd3ad196c64d3704d6560c1ae1d/src/mip/definitions/commands_3dm.h#L1917)

and C++ implementations here:
- [heading_enable](https://github.com/LORD-MicroStrain/mip_sdk/blob/2c3e4efe2d886cd3ad196c64d3704d6560c1ae1d/src/mip/definitions/commands_3dm.hpp#L2257)
- [writeComplementaryFilter](https://github.com/LORD-MicroStrain/mip_sdk/blob/2c3e4efe2d886cd3ad196c64d3704d6560c1ae1d/src/mip/definitions/commands_3dm.hpp#L2279C11-L2279C35)


Hope that helps.

**Comment by peichunhuang-1** [comment]
Thanks for your help, I have tried these command and check by readComplementaryFilter, however the behavior of sensor was not the same as I sent by SensorConnect. 

            std::unique_ptr<DeviceInterface>& device = utils->device;
            if(commands_base::ping(*device) != CmdResult::ACK_OK)
               exit_gracefully("ERROR: Could not ping the device!");
            if(commands_base::setIdle(*device) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not set the device to idle!");
            if(commands_3dm::defaultDeviceSettings(*device) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not load default device settings!");

            uint16_t sensor_base_rate;
            if(commands_3dm::imuGetBaseRate(*device, &sensor_base_rate) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not get sensor base rate format!");

            const uint16_t sensor_decimation = sensor_base_rate / sensor_sample_rate;
            std::array<DescriptorRate, 2> sensor_descriptors = {{
                { data_sensor::DATA_ACCEL_SCALED,   sensor_decimation },
                { data_sensor::DATA_GYRO_SCALED,    sensor_decimation }
            }};
            if(commands_3dm::writeImuMessageFormat(*device, sensor_descriptors.size(), sensor_descriptors.data()) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not set sensor message format!");
            float sensor_to_vehicle_transformation_euler[3] = {0, 0, 0}; // M_PI, 0, 0
            if(commands_filter::writeSensorToVehicleRotationEuler(*device, sensor_to_vehicle_transformation_euler[0], sensor_to_vehicle_transformation_euler[1], sensor_to_vehicle_transformation_euler[2]) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not set sensor-to-vehicle transformation!");
            
            uint16_t filter_base_rate;

            if(commands_3dm::filterGetBaseRate(*device, &filter_base_rate) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not get filter base rate format!");
            const uint16_t filter_decimation = filter_base_rate / filter_sample_rate;

            std::array<DescriptorRate, 4> filter_descriptors = {{
                { data_filter::DATA_FILTER_TIMESTAMP, filter_decimation },
                { data_filter::DATA_FILTER_STATUS,    filter_decimation },
                { data_filter::DATA_ATT_QUATERNION , filter_decimation },
                { data_filter::DATA_ATT_UNCERTAINTY_QUATERNION, filter_decimation},
            }};

            if(commands_3dm::writeFilterMessageFormat(*device, filter_descriptors.size(), filter_descriptors.data()) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not set filter message format!");
            if(commands_3dm::writeComplementaryFilter(*device, true, false, 10., 1.) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not set north complement off!");
            if(commands_filter::writeAutoInitControl(*device, 1) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not set filter autoinit control!");
            if(commands_filter::reset(*device) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not reset the filter!");

            bool heading_align = true, gravity_align = true;
            float heading_time, gravity_time;
            if(commands_3dm::loadComplementaryFilter(*device) != CmdResult::ACK_OK)
                exit_gracefully("ERROR: Could not load filter complement!");
            if(commands_3dm::readComplementaryFilter(*device, &gravity_align, &heading_align, &gravity_time, &heading_time) == CmdResult::ACK_OK)
                std::cout << "heading algn: " << heading_align << "\n"; // the heading align is printed as 0
                
Here is the data collected by SensorConnect with/without North compensation:
![disabled](https://github.com/LORD-MicroStrain/mip_sdk/assets/60284084/04f68088-df1a-4c98-a879-7770ad40630e)
![enabled](https://github.com/LORD-MicroStrain/mip_sdk/assets/60284084/db543646-12e1-47b1-a487-6c697a8ac9ca)

and here is the data collected by settings of my code above:
![data](https://github.com/LORD-MicroStrain/mip_sdk/assets/60284084/133212e1-66cb-455e-862d-28eda1efbf72)

**Comment by nathanmillermicrostrain** [comment]
The heading alignment disable is for the complementary filter in the sensor dataset.  Looking at your code, I think you are plotting the kalman filter data coming out of the filter descriptor set.  The complementary filter is provided as a backup to the kalman filter.  To disable the heading update for the kalman filter, you would use the Heading Update Control command and disable all heading inputs (value of 0).  Please reference the DCP here for more details: https://www.microstrain.com/sites/default/files/3dm-gx5-25_dcp_manual_8500-0065_reference_document.pdf

**Comment by peichunhuang-1** [comment]
thank you very much, I solve it.
